//
// From Localhost
//

### Get all meters via GET
GET http://localhost:8090/meters
### Get all measures via GET
GET http://localhost:8090/measures
### Get a specific meter via GET
GET http://localhost:8090/meters/1
### Create one meter via POST 
POST http://localhost:8090/meters HTTP/1.1 
content-type: application/json

{
    "id_meter" : 4, 
    "point_name": "Central Chixoy IV",
    "type_meter": "G",
    "serial_number": "SN15204099",
    "maker": "ION",
    "model": "ION1510",
    "habilitation_date": "03-01-2022",
    "state": "Active"
}
### Update a specific contact via PUT
PUT http://localhost:8090/meters/4 HTTP/1.1  
content-type: application/json

{
    "point_name": "Central Chixoy 4",
    "type_meter": "G",
    "serial_number": "SN15204099",
    "maker": "ION",
    "model": "ION1510",
    "habilitation_date": "03-01-2022",
    "state": "Active"
}
### Delete a specific meter via DELETE
DELETE http://localhost:8090/meters/4 HTTP/1.1

//
// From Render
//

// npm run swagger-autogen