// From Localhost

### Get all meters via GET
GET http://localhost:8090/meters
### Get all measures via GET
GET http://localhost:8090/measures
### Get a specific meter via GET
GET http://localhost:8090/meters/2
### Create one meter via POST 
POST http://localhost:8090/meters HTTP/1.1 
content-type: application/json

{
    "id_meter": 4,
    "point_name": "Central Chixoy IV",
    "type_meter": "G",
    "serial_number": "SN15204099",
    "maker": "ION",
    "model": "ION1510",
    "habilitation_date": "03-01-2022",
    "state": "Active"
}

// From Render
### Get all meters via GET
GET https://week05-samuel-palacios-cse341.onrender.com/meters
### Get all measures via GET
GET https://week05-samuel-palacios-cse341.onrender.com/meausres
### Get a specific meter via GET
GET https://week05-samuel-palacios-cse341.onrender.com/meters/2
### Create one meter via POST 
POST https://week05-samuel-palacios-cse341.onrender.com/meters HTTP/1.1 
content-type: application/json

{
    "id_meter": 4,
    "point_name": "Central Chixoy IV",
    "type_meter": "G",
    "serial_number": "SN15204099",
    "maker": "ION",
    "model": "ION1510",
    "habilitation_date": "03-01-2022",
    "state": "Active"
}

// npm run swagger-autogen